package tv

import "github.com/trolleyman/ottoman/internal/store"

// Export is the payload the agent serves at GET /api/tv/export so the
// controller can mirror everything it needs to drive the TVs itself when the
// agent is down: each TV's transport (host/mac) and its SSAP pairing key. The
// pairing key is generated by the TV and only ever known to the agent, so it
// can't be configured on the controller by hand — it has to be synced.
type Export struct {
	TVs []ExportTV `json:"tvs"`
}

// ExportTV is one TV's synced state: its registry identity/transport plus the
// pairing key needed to open an SSAP session.
type ExportTV struct {
	Edid         string        `json:"edid"`
	FriendlyName string        `json:"friendly_name,omitempty"`
	TV           *store.TVConn `json:"tv,omitempty"`
	PairingKey   string        `json:"pairing_key,omitempty"`
}

// Export assembles the sync payload from this manager's own registry and TV
// store, for the agent to serve to the controller.
func (m *Manager) Export() Export {
	return BuildExport(m.reg, m.store)
}

// BuildExport assembles the export payload from a monitor registry (for the TV
// transports) and a TV store (for the pairing keys).
func BuildExport(reg *store.Registry, st *store.TVStore) Export {
	entries := reg.TVEntries()
	out := Export{TVs: make([]ExportTV, 0, len(entries))}
	for _, e := range entries {
		key, _ := st.LoadPairingKey(e.Edid)
		out.TVs = append(out.TVs, ExportTV{
			Edid:         e.Edid,
			FriendlyName: e.FriendlyName,
			TV:           e.TV,
			PairingKey:   key,
		})
	}
	return out
}
