// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Layout defines model for Layout.
type Layout struct {
	Emoji    *string          `json:"emoji,omitempty"`
	Id       *string          `json:"id,omitempty"`
	Monitors *[]LayoutMonitor `json:"monitors,omitempty"`
	Name     *string          `json:"name,omitempty"`
}

// LayoutMonitor defines model for LayoutMonitor.
type LayoutMonitor struct {
	Edid        *string `json:"edid,omitempty"`
	Height      *int    `json:"height,omitempty"`
	Port        *string `json:"port,omitempty"`
	PositionX   *int    `json:"position_x,omitempty"`
	PositionY   *int    `json:"position_y,omitempty"`
	Primary     *bool   `json:"primary,omitempty"`
	RefreshRate *int    `json:"refresh_rate,omitempty"`
	Width       *int    `json:"width,omitempty"`
}

// LayoutsResponse defines model for LayoutsResponse.
type LayoutsResponse struct {
	CurrentLayout *string   `json:"current_layout,omitempty"`
	Layouts       *[]Layout `json:"layouts,omitempty"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	IpAddress string  `json:"ip_address"`
	Port      string  `json:"port"`
	Secret    *string `json:"secret,omitempty"`
	Status    string  `json:"status"`
	Uptime    string  `json:"uptime"`
	Version   string  `json:"version"`
}

// SwitchResponse defines model for SwitchResponse.
type SwitchResponse struct {
	CurrentLayout *string `json:"current_layout,omitempty"`
	Message       *string `json:"message,omitempty"`
	Success       *bool   `json:"success,omitempty"`
}

// SwitchLayoutJSONBody defines parameters for SwitchLayout.
type SwitchLayoutJSONBody struct {
	LayoutId *string `json:"layout_id,omitempty"`
}

// SwitchLayoutJSONRequestBody defines body for SwitchLayout for application/json ContentType.
type SwitchLayoutJSONRequestBody SwitchLayoutJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all layouts
	// (GET /api/layouts)
	GetLayouts(ctx echo.Context) error
	// Switch layout
	// (POST /api/layouts/switch)
	SwitchLayout(ctx echo.Context) error
	// Get system status
	// (GET /api/status)
	GetStatus(ctx echo.Context) error
	// WebSocket Trackpad Connection
	// (GET /api/trackpad)
	ConnectTrackpad(ctx echo.Context) error
	// Health check
	// (GET /health)
	CheckHealth(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetLayouts converts echo context to params.
func (w *ServerInterfaceWrapper) GetLayouts(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLayouts(ctx)
	return err
}

// SwitchLayout converts echo context to params.
func (w *ServerInterfaceWrapper) SwitchLayout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SwitchLayout(ctx)
	return err
}

// GetStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStatus(ctx)
	return err
}

// ConnectTrackpad converts echo context to params.
func (w *ServerInterfaceWrapper) ConnectTrackpad(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ConnectTrackpad(ctx)
	return err
}

// CheckHealth converts echo context to params.
func (w *ServerInterfaceWrapper) CheckHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CheckHealth(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/layouts", wrapper.GetLayouts)
	router.POST(baseURL+"/api/layouts/switch", wrapper.SwitchLayout)
	router.GET(baseURL+"/api/status", wrapper.GetStatus)
	router.GET(baseURL+"/api/trackpad", wrapper.ConnectTrackpad)
	router.GET(baseURL+"/health", wrapper.CheckHealth)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RVS08bMRD+K5bbY5QN5ZYb5dAiikCkVQ9VFRnvZNew63HHEyBC/PfK9ua53gKquDke",
	"z+N7zOZJamwdWrDs5fRJel1Dq+Lxm1rhksPJETogNhDvocVbEw68ciCn0jMZW8nnkTRl9rpFaxgpJhuG",
	"Nh4+EizkVH4otv2LrnmROl+ktFChK6mI1Cr8tqqFTKvtS7y5Bc3h6X6tPphyYOgaTFXzTshYhgriOA6J",
	"s0kOvWGDdv44lNjFVwNxMq2i3eANYgPKhiDBgsDXc1IM+fQHU3KdCw0T46/BO7Qe+tToJRFYnjcbH/Tw",
	"ptBbhe0rmptvxoqX/xjPuLkqSwLvB6QY0MiDJhgIxZbZ0NKxyXpuJO+BvEGb9yPBn6UhKOX017r8NmNT",
	"drSLppv9d46TB8O6/i/JWvBeVXkkfqn1Pp8b+/UVClfGLjC+NtyE2CUztsqKU7RM2DRA4uTqbAfxVB6N",
	"J+NJaIYOrHJGTuXxeDI+DrAV17F5oZwpdrxVJb0CUhXW56yUU/kFuLOwDDQnSuLzT5NJJAMtg42ZyrnG",
	"6Jhb3PqkVfLk6xy7tWGEXYLXZBwnRLOOtefIYJsWOIwnVNOINYwQ3cVV+Khl1BB9Bl/SutuYZCTw/BnL",
	"1ZvA7RskNZ9nv3k5iZ/fkdoDM7+a2ZTXEbvldbu8Q3aZrffv/SDtf7MykC7PMz7xK8/Qig7BBhGT0ndO",
	"lTuY9ov9cBWpErxgFD/hZob6DngsLtKKe7HApsEH8b2rMwNbnlDli/XFNej7cCG6+cdydMDaKVoLmtcJ",
	"h9wdTY76UyV9jK3EFSGjxuZQwc2sm9FE1yhUiPhrUE36L8uqeVqDvvua3ryoJ8MjF65R5kBJeFStS9+t",
	"cznqrcPL2qUBhA7DxG35GwAA//8o87nnTgkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
