//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for Modifier.
const (
	Alt   Modifier = "alt"
	Ctrl  Modifier = "ctrl"
	Meta  Modifier = "meta"
	Shift Modifier = "shift"
)

// Defines values for MouseButton.
const (
	Back    MouseButton = "back"
	Forward MouseButton = "forward"
	Left    MouseButton = "left"
	Middle  MouseButton = "middle"
	Right   MouseButton = "right"
)

// Defines values for TrackpadMessageKeyDownType.
const (
	Keydown TrackpadMessageKeyDownType = "keydown"
)

// Defines values for TrackpadMessageKeyUpType.
const (
	Keyup TrackpadMessageKeyUpType = "keyup"
)

// Defines values for TrackpadMessageMouseClickType.
const (
	Mouseclick TrackpadMessageMouseClickType = "mouseclick"
)

// Defines values for TrackpadMessageMouseDownType.
const (
	Mousedown TrackpadMessageMouseDownType = "mousedown"
)

// Defines values for TrackpadMessageMouseMoveRelativeType.
const (
	Mousemoverel TrackpadMessageMouseMoveRelativeType = "mousemoverel"
)

// Defines values for TrackpadMessageMouseMoveToType.
const (
	Mousemoveto TrackpadMessageMouseMoveToType = "mousemoveto"
)

// Defines values for TrackpadMessageMousePositionUpdateType.
const (
	Mousepositionupdate TrackpadMessageMousePositionUpdateType = "mousepositionupdate"
)

// Defines values for TrackpadMessageMouseScrollType.
const (
	Mousescroll TrackpadMessageMouseScrollType = "mousescroll"
)

// Defines values for TrackpadMessageMouseUpType.
const (
	Mouseup TrackpadMessageMouseUpType = "mouseup"
)

// Defines values for TrackpadMessageTextType.
const (
	Text TrackpadMessageTextType = "text"
)

// ActiveMonitor defines model for ActiveMonitor.
type ActiveMonitor struct {
	Height      int     `json:"height"`
	Model       string  `json:"model"`
	PositionX   int     `json:"position_x"`
	PositionY   int     `json:"position_y"`
	Primary     bool    `json:"primary"`
	RefreshRate float64 `json:"refresh_rate"`
	Width       int     `json:"width"`
}

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Token string `json:"token"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Message *string `json:"message,omitempty"`
	Success bool    `json:"success"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int     `json:"code"`
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// Layout defines model for Layout.
type Layout struct {
	Aliases  []string        `json:"aliases"`
	Emoji    *string         `json:"emoji,omitempty"`
	Id       string          `json:"id"`
	Monitors []LayoutMonitor `json:"monitors"`
	Name     string          `json:"name"`
}

// LayoutMonitor defines model for LayoutMonitor.
type LayoutMonitor struct {
	Edid        string  `json:"edid"`
	Height      int     `json:"height"`
	Name        string  `json:"name"`
	Port        string  `json:"port"`
	PositionX   int     `json:"position_x"`
	PositionY   int     `json:"position_y"`
	Primary     bool    `json:"primary"`
	RefreshRate float64 `json:"refresh_rate"`
	Width       int     `json:"width"`
}

// LayoutsResponse defines model for LayoutsResponse.
type LayoutsResponse struct {
	CurrentLayout string   `json:"current_layout"`
	Layouts       []Layout `json:"layouts"`
}

// Modifier defines model for Modifier.
type Modifier string

// Monitor defines model for Monitor.
type Monitor struct {
	Active       *ActiveMonitor `json:"active,omitempty"`
	Edid         string         `json:"edid"`
	Manufacturer string         `json:"manufacturer"`
	Name         string         `json:"name"`
	Port         string         `json:"port"`
}

// MonitorsResponse defines model for MonitorsResponse.
type MonitorsResponse = []Monitor

// MouseButton defines model for MouseButton.
type MouseButton string

// RemoveLayoutRequest defines model for RemoveLayoutRequest.
type RemoveLayoutRequest struct {
	Layout string `json:"layout"`
}

// RemoveLayoutResponse defines model for RemoveLayoutResponse.
type RemoveLayoutResponse struct {
	Message *string `json:"message,omitempty"`
	Success bool    `json:"success"`
}

// SaveLayoutRequest defines model for SaveLayoutRequest.
type SaveLayoutRequest struct {
	Emoji *string `json:"emoji,omitempty"`
	Id    *string `json:"id,omitempty"`
	Name  string  `json:"name"`
}

// SaveLayoutResponse defines model for SaveLayoutResponse.
type SaveLayoutResponse struct {
	Layout  Layout  `json:"layout"`
	Message *string `json:"message,omitempty"`
	Success bool    `json:"success"`
}

// ShutdownResponse defines model for ShutdownResponse.
type ShutdownResponse struct {
	Message *string `json:"message,omitempty"`
	Success bool    `json:"success"`
}

// SimSetStateRequest defines model for SimSetStateRequest.
type SimSetStateRequest struct {
	State string `json:"state"`
}

// SimStateResponse defines model for SimStateResponse.
type SimStateResponse struct {
	State string `json:"state"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Hostname  string                   `json:"hostname"`
	IpAddress StatusResponse_IpAddress `json:"ip_address"`
	Port      string                   `json:"port"`
	Secret    string                   `json:"secret"`
	Status    string                   `json:"status"`
	Uptime    string                   `json:"uptime"`
	Version   string                   `json:"version"`
}

// StatusResponseIpAddress0 defines model for .
type StatusResponseIpAddress0 = string

// StatusResponseIpAddress1 defines model for .
type StatusResponseIpAddress1 = string

// StatusResponse_IpAddress defines model for StatusResponse.IpAddress.
type StatusResponse_IpAddress struct {
	union json.RawMessage
}

// SwitchLayoutRequest defines model for SwitchLayoutRequest.
type SwitchLayoutRequest struct {
	Layout string `json:"layout"`
}

// SwitchLayoutResponse defines model for SwitchLayoutResponse.
type SwitchLayoutResponse struct {
	CurrentLayout string  `json:"current_layout"`
	Message       *string `json:"message,omitempty"`
	Success       bool    `json:"success"`
}

// TrackpadMessage defines model for TrackpadMessage.
type TrackpadMessage struct {
	union json.RawMessage
}

// TrackpadMessageKeyDown defines model for TrackpadMessageKeyDown.
type TrackpadMessageKeyDown struct {
	Key       string                     `json:"key"`
	Modifiers []Modifier                 `json:"modifiers"`
	Type      TrackpadMessageKeyDownType `json:"type"`
}

// TrackpadMessageKeyDownType defines model for TrackpadMessageKeyDown.Type.
type TrackpadMessageKeyDownType string

// TrackpadMessageKeyUp defines model for TrackpadMessageKeyUp.
type TrackpadMessageKeyUp struct {
	Key       string                   `json:"key"`
	Modifiers []Modifier               `json:"modifiers"`
	Type      TrackpadMessageKeyUpType `json:"type"`
}

// TrackpadMessageKeyUpType defines model for TrackpadMessageKeyUp.Type.
type TrackpadMessageKeyUpType string

// TrackpadMessageMouseClick defines model for TrackpadMessageMouseClick.
type TrackpadMessageMouseClick struct {
	Btn       MouseButton                   `json:"btn"`
	Modifiers []Modifier                    `json:"modifiers"`
	Type      TrackpadMessageMouseClickType `json:"type"`
}

// TrackpadMessageMouseClickType defines model for TrackpadMessageMouseClick.Type.
type TrackpadMessageMouseClickType string

// TrackpadMessageMouseDown defines model for TrackpadMessageMouseDown.
type TrackpadMessageMouseDown struct {
	Btn       MouseButton                  `json:"btn"`
	Modifiers []Modifier                   `json:"modifiers"`
	Type      TrackpadMessageMouseDownType `json:"type"`
}

// TrackpadMessageMouseDownType defines model for TrackpadMessageMouseDown.Type.
type TrackpadMessageMouseDownType string

// TrackpadMessageMouseMoveRelative defines model for TrackpadMessageMouseMoveRelative.
type TrackpadMessageMouseMoveRelative struct {
	Dx   float64                              `json:"dx"`
	Dy   float64                              `json:"dy"`
	Type TrackpadMessageMouseMoveRelativeType `json:"type"`
}

// TrackpadMessageMouseMoveRelativeType defines model for TrackpadMessageMouseMoveRelative.Type.
type TrackpadMessageMouseMoveRelativeType string

// TrackpadMessageMouseMoveTo defines model for TrackpadMessageMouseMoveTo.
type TrackpadMessageMouseMoveTo struct {
	Type TrackpadMessageMouseMoveToType `json:"type"`
	X    int                            `json:"x"`
	Y    int                            `json:"y"`
}

// TrackpadMessageMouseMoveToType defines model for TrackpadMessageMouseMoveTo.Type.
type TrackpadMessageMouseMoveToType string

// TrackpadMessageMousePositionUpdate defines model for TrackpadMessageMousePositionUpdate.
type TrackpadMessageMousePositionUpdate struct {
	Type TrackpadMessageMousePositionUpdateType `json:"type"`
	X    int                                    `json:"x"`
	Y    int                                    `json:"y"`
}

// TrackpadMessageMousePositionUpdateType defines model for TrackpadMessageMousePositionUpdate.Type.
type TrackpadMessageMousePositionUpdateType string

// TrackpadMessageMouseScroll defines model for TrackpadMessageMouseScroll.
type TrackpadMessageMouseScroll struct {
	Dx      float32                        `json:"dx"`
	Dy      float32                        `json:"dy"`
	Precise *bool                          `json:"precise,omitempty"`
	Type    TrackpadMessageMouseScrollType `json:"type"`
}

// TrackpadMessageMouseScrollType defines model for TrackpadMessageMouseScroll.Type.
type TrackpadMessageMouseScrollType string

// TrackpadMessageMouseUp defines model for TrackpadMessageMouseUp.
type TrackpadMessageMouseUp struct {
	Btn       MouseButton                `json:"btn"`
	Modifiers []Modifier                 `json:"modifiers"`
	Type      TrackpadMessageMouseUpType `json:"type"`
}

// TrackpadMessageMouseUpType defines model for TrackpadMessageMouseUp.Type.
type TrackpadMessageMouseUpType string

// TrackpadMessageText defines model for TrackpadMessageText.
type TrackpadMessageText struct {
	Text string                  `json:"text"`
	Type TrackpadMessageTextType `json:"type"`
}

// TrackpadMessageTextType defines model for TrackpadMessageText.Type.
type TrackpadMessageTextType string

// WakeResponse defines model for WakeResponse.
type WakeResponse struct {
	Message *string `json:"message,omitempty"`
	Success bool    `json:"success"`
}

// AuthJSONRequestBody defines body for Auth for application/json ContentType.
type AuthJSONRequestBody = AuthRequest

// RemoveLayoutJSONRequestBody defines body for RemoveLayout for application/json ContentType.
type RemoveLayoutJSONRequestBody = RemoveLayoutRequest

// SaveCurrentLayoutJSONRequestBody defines body for SaveCurrentLayout for application/json ContentType.
type SaveCurrentLayoutJSONRequestBody = SaveLayoutRequest

// SwitchLayoutJSONRequestBody defines body for SwitchLayout for application/json ContentType.
type SwitchLayoutJSONRequestBody = SwitchLayoutRequest

// SimSetStateJSONRequestBody defines body for SimSetState for application/json ContentType.
type SimSetStateJSONRequestBody = SimSetStateRequest

// AsStatusResponseIpAddress0 returns the union data inside the StatusResponse_IpAddress as a StatusResponseIpAddress0
func (t StatusResponse_IpAddress) AsStatusResponseIpAddress0() (StatusResponseIpAddress0, error) {
	var body StatusResponseIpAddress0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatusResponseIpAddress0 overwrites any union data inside the StatusResponse_IpAddress as the provided StatusResponseIpAddress0
func (t *StatusResponse_IpAddress) FromStatusResponseIpAddress0(v StatusResponseIpAddress0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatusResponseIpAddress0 performs a merge with any union data inside the StatusResponse_IpAddress, using the provided StatusResponseIpAddress0
func (t *StatusResponse_IpAddress) MergeStatusResponseIpAddress0(v StatusResponseIpAddress0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStatusResponseIpAddress1 returns the union data inside the StatusResponse_IpAddress as a StatusResponseIpAddress1
func (t StatusResponse_IpAddress) AsStatusResponseIpAddress1() (StatusResponseIpAddress1, error) {
	var body StatusResponseIpAddress1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatusResponseIpAddress1 overwrites any union data inside the StatusResponse_IpAddress as the provided StatusResponseIpAddress1
func (t *StatusResponse_IpAddress) FromStatusResponseIpAddress1(v StatusResponseIpAddress1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatusResponseIpAddress1 performs a merge with any union data inside the StatusResponse_IpAddress, using the provided StatusResponseIpAddress1
func (t *StatusResponse_IpAddress) MergeStatusResponseIpAddress1(v StatusResponseIpAddress1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StatusResponse_IpAddress) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StatusResponse_IpAddress) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsTrackpadMessageMousePositionUpdate returns the union data inside the TrackpadMessage as a TrackpadMessageMousePositionUpdate
func (t TrackpadMessage) AsTrackpadMessageMousePositionUpdate() (TrackpadMessageMousePositionUpdate, error) {
	var body TrackpadMessageMousePositionUpdate
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackpadMessageMousePositionUpdate overwrites any union data inside the TrackpadMessage as the provided TrackpadMessageMousePositionUpdate
func (t *TrackpadMessage) FromTrackpadMessageMousePositionUpdate(v TrackpadMessageMousePositionUpdate) error {
	v.Type = "mousepositionupdate"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackpadMessageMousePositionUpdate performs a merge with any union data inside the TrackpadMessage, using the provided TrackpadMessageMousePositionUpdate
func (t *TrackpadMessage) MergeTrackpadMessageMousePositionUpdate(v TrackpadMessageMousePositionUpdate) error {
	v.Type = "mousepositionupdate"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackpadMessageMouseMoveRelative returns the union data inside the TrackpadMessage as a TrackpadMessageMouseMoveRelative
func (t TrackpadMessage) AsTrackpadMessageMouseMoveRelative() (TrackpadMessageMouseMoveRelative, error) {
	var body TrackpadMessageMouseMoveRelative
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackpadMessageMouseMoveRelative overwrites any union data inside the TrackpadMessage as the provided TrackpadMessageMouseMoveRelative
func (t *TrackpadMessage) FromTrackpadMessageMouseMoveRelative(v TrackpadMessageMouseMoveRelative) error {
	v.Type = "mousemoverel"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackpadMessageMouseMoveRelative performs a merge with any union data inside the TrackpadMessage, using the provided TrackpadMessageMouseMoveRelative
func (t *TrackpadMessage) MergeTrackpadMessageMouseMoveRelative(v TrackpadMessageMouseMoveRelative) error {
	v.Type = "mousemoverel"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackpadMessageMouseMoveTo returns the union data inside the TrackpadMessage as a TrackpadMessageMouseMoveTo
func (t TrackpadMessage) AsTrackpadMessageMouseMoveTo() (TrackpadMessageMouseMoveTo, error) {
	var body TrackpadMessageMouseMoveTo
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackpadMessageMouseMoveTo overwrites any union data inside the TrackpadMessage as the provided TrackpadMessageMouseMoveTo
func (t *TrackpadMessage) FromTrackpadMessageMouseMoveTo(v TrackpadMessageMouseMoveTo) error {
	v.Type = "mousemoveto"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackpadMessageMouseMoveTo performs a merge with any union data inside the TrackpadMessage, using the provided TrackpadMessageMouseMoveTo
func (t *TrackpadMessage) MergeTrackpadMessageMouseMoveTo(v TrackpadMessageMouseMoveTo) error {
	v.Type = "mousemoveto"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackpadMessageMouseClick returns the union data inside the TrackpadMessage as a TrackpadMessageMouseClick
func (t TrackpadMessage) AsTrackpadMessageMouseClick() (TrackpadMessageMouseClick, error) {
	var body TrackpadMessageMouseClick
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackpadMessageMouseClick overwrites any union data inside the TrackpadMessage as the provided TrackpadMessageMouseClick
func (t *TrackpadMessage) FromTrackpadMessageMouseClick(v TrackpadMessageMouseClick) error {
	v.Type = "mouseclick"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackpadMessageMouseClick performs a merge with any union data inside the TrackpadMessage, using the provided TrackpadMessageMouseClick
func (t *TrackpadMessage) MergeTrackpadMessageMouseClick(v TrackpadMessageMouseClick) error {
	v.Type = "mouseclick"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackpadMessageMouseDown returns the union data inside the TrackpadMessage as a TrackpadMessageMouseDown
func (t TrackpadMessage) AsTrackpadMessageMouseDown() (TrackpadMessageMouseDown, error) {
	var body TrackpadMessageMouseDown
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackpadMessageMouseDown overwrites any union data inside the TrackpadMessage as the provided TrackpadMessageMouseDown
func (t *TrackpadMessage) FromTrackpadMessageMouseDown(v TrackpadMessageMouseDown) error {
	v.Type = "mousedown"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackpadMessageMouseDown performs a merge with any union data inside the TrackpadMessage, using the provided TrackpadMessageMouseDown
func (t *TrackpadMessage) MergeTrackpadMessageMouseDown(v TrackpadMessageMouseDown) error {
	v.Type = "mousedown"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackpadMessageMouseUp returns the union data inside the TrackpadMessage as a TrackpadMessageMouseUp
func (t TrackpadMessage) AsTrackpadMessageMouseUp() (TrackpadMessageMouseUp, error) {
	var body TrackpadMessageMouseUp
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackpadMessageMouseUp overwrites any union data inside the TrackpadMessage as the provided TrackpadMessageMouseUp
func (t *TrackpadMessage) FromTrackpadMessageMouseUp(v TrackpadMessageMouseUp) error {
	v.Type = "mouseup"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackpadMessageMouseUp performs a merge with any union data inside the TrackpadMessage, using the provided TrackpadMessageMouseUp
func (t *TrackpadMessage) MergeTrackpadMessageMouseUp(v TrackpadMessageMouseUp) error {
	v.Type = "mouseup"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackpadMessageMouseScroll returns the union data inside the TrackpadMessage as a TrackpadMessageMouseScroll
func (t TrackpadMessage) AsTrackpadMessageMouseScroll() (TrackpadMessageMouseScroll, error) {
	var body TrackpadMessageMouseScroll
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackpadMessageMouseScroll overwrites any union data inside the TrackpadMessage as the provided TrackpadMessageMouseScroll
func (t *TrackpadMessage) FromTrackpadMessageMouseScroll(v TrackpadMessageMouseScroll) error {
	v.Type = "mousescroll"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackpadMessageMouseScroll performs a merge with any union data inside the TrackpadMessage, using the provided TrackpadMessageMouseScroll
func (t *TrackpadMessage) MergeTrackpadMessageMouseScroll(v TrackpadMessageMouseScroll) error {
	v.Type = "mousescroll"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackpadMessageKeyDown returns the union data inside the TrackpadMessage as a TrackpadMessageKeyDown
func (t TrackpadMessage) AsTrackpadMessageKeyDown() (TrackpadMessageKeyDown, error) {
	var body TrackpadMessageKeyDown
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackpadMessageKeyDown overwrites any union data inside the TrackpadMessage as the provided TrackpadMessageKeyDown
func (t *TrackpadMessage) FromTrackpadMessageKeyDown(v TrackpadMessageKeyDown) error {
	v.Type = "keydown"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackpadMessageKeyDown performs a merge with any union data inside the TrackpadMessage, using the provided TrackpadMessageKeyDown
func (t *TrackpadMessage) MergeTrackpadMessageKeyDown(v TrackpadMessageKeyDown) error {
	v.Type = "keydown"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackpadMessageKeyUp returns the union data inside the TrackpadMessage as a TrackpadMessageKeyUp
func (t TrackpadMessage) AsTrackpadMessageKeyUp() (TrackpadMessageKeyUp, error) {
	var body TrackpadMessageKeyUp
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackpadMessageKeyUp overwrites any union data inside the TrackpadMessage as the provided TrackpadMessageKeyUp
func (t *TrackpadMessage) FromTrackpadMessageKeyUp(v TrackpadMessageKeyUp) error {
	v.Type = "keyup"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackpadMessageKeyUp performs a merge with any union data inside the TrackpadMessage, using the provided TrackpadMessageKeyUp
func (t *TrackpadMessage) MergeTrackpadMessageKeyUp(v TrackpadMessageKeyUp) error {
	v.Type = "keyup"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackpadMessageText returns the union data inside the TrackpadMessage as a TrackpadMessageText
func (t TrackpadMessage) AsTrackpadMessageText() (TrackpadMessageText, error) {
	var body TrackpadMessageText
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackpadMessageText overwrites any union data inside the TrackpadMessage as the provided TrackpadMessageText
func (t *TrackpadMessage) FromTrackpadMessageText(v TrackpadMessageText) error {
	v.Type = "text"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackpadMessageText performs a merge with any union data inside the TrackpadMessage, using the provided TrackpadMessageText
func (t *TrackpadMessage) MergeTrackpadMessageText(v TrackpadMessageText) error {
	v.Type = "text"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t TrackpadMessage) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t TrackpadMessage) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "keydown":
		return t.AsTrackpadMessageKeyDown()
	case "keyup":
		return t.AsTrackpadMessageKeyUp()
	case "mouseclick":
		return t.AsTrackpadMessageMouseClick()
	case "mousedown":
		return t.AsTrackpadMessageMouseDown()
	case "mousemoverel":
		return t.AsTrackpadMessageMouseMoveRelative()
	case "mousemoveto":
		return t.AsTrackpadMessageMouseMoveTo()
	case "mousepositionupdate":
		return t.AsTrackpadMessageMousePositionUpdate()
	case "mousescroll":
		return t.AsTrackpadMessageMouseScroll()
	case "mouseup":
		return t.AsTrackpadMessageMouseUp()
	case "text":
		return t.AsTrackpadMessageText()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t TrackpadMessage) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *TrackpadMessage) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate
	// (POST /api/auth)
	Auth(w http.ResponseWriter, r *http.Request)
	// Check authentication status
	// (GET /api/auth/check)
	CheckAuth(w http.ResponseWriter, r *http.Request)
	// Logout
	// (POST /api/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get all layouts
	// (GET /api/layouts)
	GetLayouts(w http.ResponseWriter, r *http.Request)
	// Get current layout
	// (GET /api/layouts/current)
	GetCurrentLayout(w http.ResponseWriter, r *http.Request)
	// Remove layout
	// (POST /api/layouts/remove)
	RemoveLayout(w http.ResponseWriter, r *http.Request)
	// Save current layout
	// (POST /api/layouts/save-current)
	SaveCurrentLayout(w http.ResponseWriter, r *http.Request)
	// Switch layout
	// (POST /api/layouts/switch)
	SwitchLayout(w http.ResponseWriter, r *http.Request)
	// Get all monitors
	// (GET /api/monitors)
	GetMonitors(w http.ResponseWriter, r *http.Request)
	// Shutdown client
	// (POST /api/shutdown)
	Shutdown(w http.ResponseWriter, r *http.Request)
	// Reset simulation
	// (POST /api/sim/reset)
	SimReset(w http.ResponseWriter, r *http.Request)
	// Set simulation state
	// (POST /api/sim/set-state)
	SimSetState(w http.ResponseWriter, r *http.Request)
	// Get simulation state
	// (GET /api/sim/state)
	SimState(w http.ResponseWriter, r *http.Request)
	// Get system status
	// (GET /api/status)
	GetStatus(w http.ResponseWriter, r *http.Request)
	// Get agent status
	// (GET /api/status/agent)
	GetAgentStatus(w http.ResponseWriter, r *http.Request)
	// WebSocket Trackpad Connection
	// (GET /api/trackpad)
	ConnectTrackpad(w http.ResponseWriter, r *http.Request)
	// Wake agent on LAN
	// (POST /api/wake)
	Wake(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	CheckHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Auth operation middleware
func (siw *ServerInterfaceWrapper) Auth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Auth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckAuth operation middleware
func (siw *ServerInterfaceWrapper) CheckAuth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckAuth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLayouts operation middleware
func (siw *ServerInterfaceWrapper) GetLayouts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLayouts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentLayout operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentLayout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentLayout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveLayout operation middleware
func (siw *ServerInterfaceWrapper) RemoveLayout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveLayout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SaveCurrentLayout operation middleware
func (siw *ServerInterfaceWrapper) SaveCurrentLayout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SaveCurrentLayout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SwitchLayout operation middleware
func (siw *ServerInterfaceWrapper) SwitchLayout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SwitchLayout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMonitors operation middleware
func (siw *ServerInterfaceWrapper) GetMonitors(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMonitors(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Shutdown operation middleware
func (siw *ServerInterfaceWrapper) Shutdown(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Shutdown(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SimReset operation middleware
func (siw *ServerInterfaceWrapper) SimReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SimReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SimSetState operation middleware
func (siw *ServerInterfaceWrapper) SimSetState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SimSetState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SimState operation middleware
func (siw *ServerInterfaceWrapper) SimState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SimState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAgentStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAgentStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAgentStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConnectTrackpad operation middleware
func (siw *ServerInterfaceWrapper) ConnectTrackpad(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConnectTrackpad(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Wake operation middleware
func (siw *ServerInterfaceWrapper) Wake(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Wake(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckHealth operation middleware
func (siw *ServerInterfaceWrapper) CheckHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/auth", wrapper.Auth)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/check", wrapper.CheckAuth)
	m.HandleFunc("POST "+options.BaseURL+"/api/auth/logout", wrapper.Logout)
	m.HandleFunc("GET "+options.BaseURL+"/api/layouts", wrapper.GetLayouts)
	m.HandleFunc("GET "+options.BaseURL+"/api/layouts/current", wrapper.GetCurrentLayout)
	m.HandleFunc("POST "+options.BaseURL+"/api/layouts/remove", wrapper.RemoveLayout)
	m.HandleFunc("POST "+options.BaseURL+"/api/layouts/save-current", wrapper.SaveCurrentLayout)
	m.HandleFunc("POST "+options.BaseURL+"/api/layouts/switch", wrapper.SwitchLayout)
	m.HandleFunc("GET "+options.BaseURL+"/api/monitors", wrapper.GetMonitors)
	m.HandleFunc("POST "+options.BaseURL+"/api/shutdown", wrapper.Shutdown)
	m.HandleFunc("POST "+options.BaseURL+"/api/sim/reset", wrapper.SimReset)
	m.HandleFunc("POST "+options.BaseURL+"/api/sim/set-state", wrapper.SimSetState)
	m.HandleFunc("GET "+options.BaseURL+"/api/sim/state", wrapper.SimState)
	m.HandleFunc("GET "+options.BaseURL+"/api/status", wrapper.GetStatus)
	m.HandleFunc("GET "+options.BaseURL+"/api/status/agent", wrapper.GetAgentStatus)
	m.HandleFunc("GET "+options.BaseURL+"/api/trackpad", wrapper.ConnectTrackpad)
	m.HandleFunc("POST "+options.BaseURL+"/api/wake", wrapper.Wake)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.CheckHealth)

	return m
}

type AuthRequestObject struct {
	Body *AuthJSONRequestBody
}

type AuthResponseObject interface {
	VisitAuthResponse(w http.ResponseWriter) error
}

type Auth200JSONResponse AuthResponse

func (response Auth200JSONResponse) VisitAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Auth401JSONResponse AuthResponse

func (response Auth401JSONResponse) VisitAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CheckAuthRequestObject struct {
}

type CheckAuthResponseObject interface {
	VisitCheckAuthResponse(w http.ResponseWriter) error
}

type CheckAuth200JSONResponse struct {
	// Authenticated Whether the user is authenticated.
	Authenticated *bool `json:"authenticated,omitempty"`
}

func (response CheckAuth200JSONResponse) VisitCheckAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CheckAuth401JSONResponse ErrorResponse

func (response CheckAuth401JSONResponse) VisitCheckAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200JSONResponse AuthResponse

func (response Logout200JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLayoutsRequestObject struct {
}

type GetLayoutsResponseObject interface {
	VisitGetLayoutsResponse(w http.ResponseWriter) error
}

type GetLayouts200JSONResponse LayoutsResponse

func (response GetLayouts200JSONResponse) VisitGetLayoutsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLayouts401JSONResponse ErrorResponse

func (response GetLayouts401JSONResponse) VisitGetLayoutsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetLayouts502JSONResponse ErrorResponse

func (response GetLayouts502JSONResponse) VisitGetLayoutsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentLayoutRequestObject struct {
}

type GetCurrentLayoutResponseObject interface {
	VisitGetCurrentLayoutResponse(w http.ResponseWriter) error
}

type GetCurrentLayout200JSONResponse SwitchLayoutResponse

func (response GetCurrentLayout200JSONResponse) VisitGetCurrentLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentLayout401JSONResponse ErrorResponse

func (response GetCurrentLayout401JSONResponse) VisitGetCurrentLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentLayout502JSONResponse ErrorResponse

func (response GetCurrentLayout502JSONResponse) VisitGetCurrentLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

type RemoveLayoutRequestObject struct {
	Body *RemoveLayoutJSONRequestBody
}

type RemoveLayoutResponseObject interface {
	VisitRemoveLayoutResponse(w http.ResponseWriter) error
}

type RemoveLayout200JSONResponse RemoveLayoutResponse

func (response RemoveLayout200JSONResponse) VisitRemoveLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RemoveLayout400JSONResponse ErrorResponse

func (response RemoveLayout400JSONResponse) VisitRemoveLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RemoveLayout401JSONResponse ErrorResponse

func (response RemoveLayout401JSONResponse) VisitRemoveLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RemoveLayout404JSONResponse ErrorResponse

func (response RemoveLayout404JSONResponse) VisitRemoveLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RemoveLayout500JSONResponse ErrorResponse

func (response RemoveLayout500JSONResponse) VisitRemoveLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RemoveLayout502JSONResponse ErrorResponse

func (response RemoveLayout502JSONResponse) VisitRemoveLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

type SaveCurrentLayoutRequestObject struct {
	Body *SaveCurrentLayoutJSONRequestBody
}

type SaveCurrentLayoutResponseObject interface {
	VisitSaveCurrentLayoutResponse(w http.ResponseWriter) error
}

type SaveCurrentLayout200JSONResponse SaveLayoutResponse

func (response SaveCurrentLayout200JSONResponse) VisitSaveCurrentLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SaveCurrentLayout400JSONResponse ErrorResponse

func (response SaveCurrentLayout400JSONResponse) VisitSaveCurrentLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SaveCurrentLayout401JSONResponse ErrorResponse

func (response SaveCurrentLayout401JSONResponse) VisitSaveCurrentLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SaveCurrentLayout500JSONResponse ErrorResponse

func (response SaveCurrentLayout500JSONResponse) VisitSaveCurrentLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SaveCurrentLayout502JSONResponse ErrorResponse

func (response SaveCurrentLayout502JSONResponse) VisitSaveCurrentLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

type SwitchLayoutRequestObject struct {
	Body *SwitchLayoutJSONRequestBody
}

type SwitchLayoutResponseObject interface {
	VisitSwitchLayoutResponse(w http.ResponseWriter) error
}

type SwitchLayout200JSONResponse SwitchLayoutResponse

func (response SwitchLayout200JSONResponse) VisitSwitchLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SwitchLayout400JSONResponse ErrorResponse

func (response SwitchLayout400JSONResponse) VisitSwitchLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SwitchLayout401JSONResponse ErrorResponse

func (response SwitchLayout401JSONResponse) VisitSwitchLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SwitchLayout404JSONResponse ErrorResponse

func (response SwitchLayout404JSONResponse) VisitSwitchLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SwitchLayout500JSONResponse ErrorResponse

func (response SwitchLayout500JSONResponse) VisitSwitchLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SwitchLayout502JSONResponse ErrorResponse

func (response SwitchLayout502JSONResponse) VisitSwitchLayoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

type GetMonitorsRequestObject struct {
}

type GetMonitorsResponseObject interface {
	VisitGetMonitorsResponse(w http.ResponseWriter) error
}

type GetMonitors200JSONResponse MonitorsResponse

func (response GetMonitors200JSONResponse) VisitGetMonitorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMonitors401JSONResponse ErrorResponse

func (response GetMonitors401JSONResponse) VisitGetMonitorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetMonitors502JSONResponse ErrorResponse

func (response GetMonitors502JSONResponse) VisitGetMonitorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

type ShutdownRequestObject struct {
}

type ShutdownResponseObject interface {
	VisitShutdownResponse(w http.ResponseWriter) error
}

type Shutdown200JSONResponse ShutdownResponse

func (response Shutdown200JSONResponse) VisitShutdownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Shutdown401JSONResponse ErrorResponse

func (response Shutdown401JSONResponse) VisitShutdownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Shutdown502JSONResponse ErrorResponse

func (response Shutdown502JSONResponse) VisitShutdownResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

type SimResetRequestObject struct {
}

type SimResetResponseObject interface {
	VisitSimResetResponse(w http.ResponseWriter) error
}

type SimReset200JSONResponse SimStateResponse

func (response SimReset200JSONResponse) VisitSimResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SimReset404JSONResponse ErrorResponse

func (response SimReset404JSONResponse) VisitSimResetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SimSetStateRequestObject struct {
	Body *SimSetStateJSONRequestBody
}

type SimSetStateResponseObject interface {
	VisitSimSetStateResponse(w http.ResponseWriter) error
}

type SimSetState200JSONResponse SimStateResponse

func (response SimSetState200JSONResponse) VisitSimSetStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SimSetState404JSONResponse ErrorResponse

func (response SimSetState404JSONResponse) VisitSimSetStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SimStateRequestObject struct {
}

type SimStateResponseObject interface {
	VisitSimStateResponse(w http.ResponseWriter) error
}

type SimState200JSONResponse SimStateResponse

func (response SimState200JSONResponse) VisitSimStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SimState404JSONResponse ErrorResponse

func (response SimState404JSONResponse) VisitSimStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetStatusRequestObject struct {
}

type GetStatusResponseObject interface {
	VisitGetStatusResponse(w http.ResponseWriter) error
}

type GetStatus200JSONResponse StatusResponse

func (response GetStatus200JSONResponse) VisitGetStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentStatusRequestObject struct {
}

type GetAgentStatusResponseObject interface {
	VisitGetAgentStatusResponse(w http.ResponseWriter) error
}

type GetAgentStatus200JSONResponse StatusResponse

func (response GetAgentStatus200JSONResponse) VisitGetAgentStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentStatus401JSONResponse ErrorResponse

func (response GetAgentStatus401JSONResponse) VisitGetAgentStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetAgentStatus502JSONResponse ErrorResponse

func (response GetAgentStatus502JSONResponse) VisitGetAgentStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)

	return json.NewEncoder(w).Encode(response)
}

type ConnectTrackpadRequestObject struct {
}

type ConnectTrackpadResponseObject interface {
	VisitConnectTrackpadResponse(w http.ResponseWriter) error
}

type ConnectTrackpad101Response struct {
}

func (response ConnectTrackpad101Response) VisitConnectTrackpadResponse(w http.ResponseWriter) error {
	w.WriteHeader(101)
	return nil
}

type WakeRequestObject struct {
}

type WakeResponseObject interface {
	VisitWakeResponse(w http.ResponseWriter) error
}

type Wake200JSONResponse WakeResponse

func (response Wake200JSONResponse) VisitWakeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Wake401JSONResponse ErrorResponse

func (response Wake401JSONResponse) VisitWakeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Wake404JSONResponse ErrorResponse

func (response Wake404JSONResponse) VisitWakeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type Wake500JSONResponse ErrorResponse

func (response Wake500JSONResponse) VisitWakeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CheckHealthRequestObject struct {
}

type CheckHealthResponseObject interface {
	VisitCheckHealthResponse(w http.ResponseWriter) error
}

type CheckHealth200TextResponse string

func (response CheckHealth200TextResponse) VisitCheckHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate
	// (POST /api/auth)
	Auth(ctx context.Context, request AuthRequestObject) (AuthResponseObject, error)
	// Check authentication status
	// (GET /api/auth/check)
	CheckAuth(ctx context.Context, request CheckAuthRequestObject) (CheckAuthResponseObject, error)
	// Logout
	// (POST /api/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get all layouts
	// (GET /api/layouts)
	GetLayouts(ctx context.Context, request GetLayoutsRequestObject) (GetLayoutsResponseObject, error)
	// Get current layout
	// (GET /api/layouts/current)
	GetCurrentLayout(ctx context.Context, request GetCurrentLayoutRequestObject) (GetCurrentLayoutResponseObject, error)
	// Remove layout
	// (POST /api/layouts/remove)
	RemoveLayout(ctx context.Context, request RemoveLayoutRequestObject) (RemoveLayoutResponseObject, error)
	// Save current layout
	// (POST /api/layouts/save-current)
	SaveCurrentLayout(ctx context.Context, request SaveCurrentLayoutRequestObject) (SaveCurrentLayoutResponseObject, error)
	// Switch layout
	// (POST /api/layouts/switch)
	SwitchLayout(ctx context.Context, request SwitchLayoutRequestObject) (SwitchLayoutResponseObject, error)
	// Get all monitors
	// (GET /api/monitors)
	GetMonitors(ctx context.Context, request GetMonitorsRequestObject) (GetMonitorsResponseObject, error)
	// Shutdown client
	// (POST /api/shutdown)
	Shutdown(ctx context.Context, request ShutdownRequestObject) (ShutdownResponseObject, error)
	// Reset simulation
	// (POST /api/sim/reset)
	SimReset(ctx context.Context, request SimResetRequestObject) (SimResetResponseObject, error)
	// Set simulation state
	// (POST /api/sim/set-state)
	SimSetState(ctx context.Context, request SimSetStateRequestObject) (SimSetStateResponseObject, error)
	// Get simulation state
	// (GET /api/sim/state)
	SimState(ctx context.Context, request SimStateRequestObject) (SimStateResponseObject, error)
	// Get system status
	// (GET /api/status)
	GetStatus(ctx context.Context, request GetStatusRequestObject) (GetStatusResponseObject, error)
	// Get agent status
	// (GET /api/status/agent)
	GetAgentStatus(ctx context.Context, request GetAgentStatusRequestObject) (GetAgentStatusResponseObject, error)
	// WebSocket Trackpad Connection
	// (GET /api/trackpad)
	ConnectTrackpad(ctx context.Context, request ConnectTrackpadRequestObject) (ConnectTrackpadResponseObject, error)
	// Wake agent on LAN
	// (POST /api/wake)
	Wake(ctx context.Context, request WakeRequestObject) (WakeResponseObject, error)
	// Health check
	// (GET /health)
	CheckHealth(ctx context.Context, request CheckHealthRequestObject) (CheckHealthResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Auth operation middleware
func (sh *strictHandler) Auth(w http.ResponseWriter, r *http.Request) {
	var request AuthRequestObject

	var body AuthJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Auth(ctx, request.(AuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Auth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthResponseObject); ok {
		if err := validResponse.VisitAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CheckAuth operation middleware
func (sh *strictHandler) CheckAuth(w http.ResponseWriter, r *http.Request) {
	var request CheckAuthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CheckAuth(ctx, request.(CheckAuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckAuth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckAuthResponseObject); ok {
		if err := validResponse.VisitCheckAuthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLayouts operation middleware
func (sh *strictHandler) GetLayouts(w http.ResponseWriter, r *http.Request) {
	var request GetLayoutsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLayouts(ctx, request.(GetLayoutsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLayouts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLayoutsResponseObject); ok {
		if err := validResponse.VisitGetLayoutsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentLayout operation middleware
func (sh *strictHandler) GetCurrentLayout(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentLayoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentLayout(ctx, request.(GetCurrentLayoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentLayout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentLayoutResponseObject); ok {
		if err := validResponse.VisitGetCurrentLayoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveLayout operation middleware
func (sh *strictHandler) RemoveLayout(w http.ResponseWriter, r *http.Request) {
	var request RemoveLayoutRequestObject

	var body RemoveLayoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveLayout(ctx, request.(RemoveLayoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveLayout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RemoveLayoutResponseObject); ok {
		if err := validResponse.VisitRemoveLayoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SaveCurrentLayout operation middleware
func (sh *strictHandler) SaveCurrentLayout(w http.ResponseWriter, r *http.Request) {
	var request SaveCurrentLayoutRequestObject

	var body SaveCurrentLayoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SaveCurrentLayout(ctx, request.(SaveCurrentLayoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SaveCurrentLayout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SaveCurrentLayoutResponseObject); ok {
		if err := validResponse.VisitSaveCurrentLayoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SwitchLayout operation middleware
func (sh *strictHandler) SwitchLayout(w http.ResponseWriter, r *http.Request) {
	var request SwitchLayoutRequestObject

	var body SwitchLayoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SwitchLayout(ctx, request.(SwitchLayoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SwitchLayout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SwitchLayoutResponseObject); ok {
		if err := validResponse.VisitSwitchLayoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMonitors operation middleware
func (sh *strictHandler) GetMonitors(w http.ResponseWriter, r *http.Request) {
	var request GetMonitorsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMonitors(ctx, request.(GetMonitorsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMonitors")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMonitorsResponseObject); ok {
		if err := validResponse.VisitGetMonitorsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Shutdown operation middleware
func (sh *strictHandler) Shutdown(w http.ResponseWriter, r *http.Request) {
	var request ShutdownRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Shutdown(ctx, request.(ShutdownRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Shutdown")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ShutdownResponseObject); ok {
		if err := validResponse.VisitShutdownResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SimReset operation middleware
func (sh *strictHandler) SimReset(w http.ResponseWriter, r *http.Request) {
	var request SimResetRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SimReset(ctx, request.(SimResetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SimReset")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SimResetResponseObject); ok {
		if err := validResponse.VisitSimResetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SimSetState operation middleware
func (sh *strictHandler) SimSetState(w http.ResponseWriter, r *http.Request) {
	var request SimSetStateRequestObject

	var body SimSetStateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SimSetState(ctx, request.(SimSetStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SimSetState")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SimSetStateResponseObject); ok {
		if err := validResponse.VisitSimSetStateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SimState operation middleware
func (sh *strictHandler) SimState(w http.ResponseWriter, r *http.Request) {
	var request SimStateRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SimState(ctx, request.(SimStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SimState")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SimStateResponseObject); ok {
		if err := validResponse.VisitSimStateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStatus operation middleware
func (sh *strictHandler) GetStatus(w http.ResponseWriter, r *http.Request) {
	var request GetStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatus(ctx, request.(GetStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatusResponseObject); ok {
		if err := validResponse.VisitGetStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAgentStatus operation middleware
func (sh *strictHandler) GetAgentStatus(w http.ResponseWriter, r *http.Request) {
	var request GetAgentStatusRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAgentStatus(ctx, request.(GetAgentStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAgentStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAgentStatusResponseObject); ok {
		if err := validResponse.VisitGetAgentStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConnectTrackpad operation middleware
func (sh *strictHandler) ConnectTrackpad(w http.ResponseWriter, r *http.Request) {
	var request ConnectTrackpadRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConnectTrackpad(ctx, request.(ConnectTrackpadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConnectTrackpad")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConnectTrackpadResponseObject); ok {
		if err := validResponse.VisitConnectTrackpadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Wake operation middleware
func (sh *strictHandler) Wake(w http.ResponseWriter, r *http.Request) {
	var request WakeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Wake(ctx, request.(WakeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Wake")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(WakeResponseObject); ok {
		if err := validResponse.VisitWakeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CheckHealth operation middleware
func (sh *strictHandler) CheckHealth(w http.ResponseWriter, r *http.Request) {
	var request CheckHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CheckHealth(ctx, request.(CheckHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckHealthResponseObject); ok {
		if err := validResponse.VisitCheckHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
